### ISSUE TITLE
I want to use it with SimHub

### ISSUE THREAD

**Issue by tosond** [vthinsel/GT7Proxy#1]
SimHub has port forwarding function

PlayStation 4/5 (port 33749) -> Simhub (port 33740) -> GT7Proxy (port 33900) -> XSim plugin (port 33800)

Can you modify it like this?

**Comment by vthinsel** [comment]
The only thing you cannot change in the code is the xsim port. Otherwise feel free to change the ports in the code.

**Comment by tosond** [comment]
How do I change the code? Even if you go into edit and change it, it doesn't apply

**Comment by vthinsel** [comment]
Best is that you download/clone the repo on your side and change the code as you want. Do not change the code here.

**Comment by tosond** [comment]
Have you ever used Gran Turismo 7 with SimHub? Port change not possible in simtool

**Comment by vthinsel** [comment]
No, I'm not using SimHub at all. Yes, port is fixed in simtool. GT7proxy expects UDP on 33740 too, as defined in the code ReceivePort = 33740. You can change it to 33900 if you need

**Comment by tosond** [comment]
I will solve it as you told me. Thank you for making this program

**Comment by vthinsel** [comment]
specific request
