### ISSUE TITLE
Cannot connect to my ps4. Have static addresses in pc and ps4. 

### ISSUE THREAD

**Issue by JacquesSakkie** [vthinsel/GT7Proxy#4]
I have tried another proxy and it works. This proxy keeps showing it cannot connect with time out. Am I doing something wrong?

**Comment by JacquesSakkie** [comment]
![snip1](https://github.com/vthinsel/GT7Proxy/assets/159711069/2648a83a-dff2-45c4-bcaa-8ca6e9814fe9)

**Comment by vthinsel** [comment]
Output is not good. Try with terminal instead so you have the same display as in the screenshots. You use it with simtools on the other side ? I didn't test on ps4 but it should be ok.

**Comment by vthinsel** [comment]
You also use an old version
